spring.application.name=prueba

spring.cloud.config.enabled=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=${GESTOPAGO_AUTH_ID_DISTRIBUIDOR}
gestopago.auth.codigo-dispositivo=${GESTOPAGO_AUTH_CODIGO_DISPOSITIVO}
gestopago.auth.password=${GESTOPAGO_AUTH_PASSWORD}
gestopago.auth.refresh-rate-ms=3600000

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
gestopago.catalog.path=/sistema/service/getProductList.do
gestopago.catalog.connect-timeout-ms=5000
gestopago.catalog.read-timeout-ms=15000